name: dart_mysql
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: Thiago Soares Figueiredo <thiagosf.dev@gmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  sqljocky5: ^2.2.1

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.5.0
